language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran"
before_install:
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- no_open_mp ;
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- travis_wait 100 R CMD INSTALL --build ${PKG_TARBALL}
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: VfdYB/eshQ2/iTgcBFFZoPf+hCNMB0n+1bkVI+uh0N0Z9awvOKdHAELkBvjCLHks3ggu8S3zL6SHN2utr27hMQOCVrfniplL6yHDvia/sAJ8i4TdtCNq+JFi6A2+rVrIM71f3y1Uyd+zC2xBGeJD3Tus1OWL+NOBe9TwPaEmPvNZvSO4/AYWacNNNmk8VmH/7tygKMEv91gVgWCtcNEzy4ELNT8ORnvPGikbYMic3Zsj/8WvyMaISGxMuQMdrH9SCz4xmFiL4LeGiTdfpWMldEYXLgrA39f4NbEd5JvwQr+Aqp1I2OB4wJXWDXiSSW/KQ+cz3ynDQ6VDtdwgfe/49bmokghYlCngsm1d3dI1yRwYoHYDE50qNE+9PR8S5v3a50+6PEMVhHDM78c0BV3S7p/fw30ez5MuLIMdLGA6tbCXl5PcDbkkaIiVQ+AqbPmN/LzE3wRyUJUtDEdYd8jI8+HBbrAcne9k2grMuozh5I20zBvnupEF/cZt9CbXYVUNAIQoW/5Xf60VRk4U22OCj3CNG8WDyvdhI2/iPOs531NQgDlPn5TnvtKyGDluHfGQp/CZcpjXlKG2AKeCBEUNsukXJh07BY2/f+asIWcaj6Bj3lf3ES7uShZgO1XjGwDIfyEHuQKcHQ8aSS97XsnpQSGhBtDh5gRlq75YAQwqhIQ=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then Rscript -e 'covr::coveralls(type =
  "all")' ; fi
