language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran --install-args=--build"
before_install:
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; fi
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
- if [[ "${PACKAGE_NAME}" == "ROpenCVLite" ]]; then shopt -s expand_aliases ; x=`Rscript
  -e "cat(Sys.which('R'))"` ; alias R="travis_wait 100 ${x}" ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: SEGF5FrC4ymnO7zvbjTxP113sMKGkwAscjDruxyzzTo7a3EIIhIo04xvVOEOwU+WlWIL6JX4Orc6lS5HwyJG2QR/oejc0VEqjHx4aLcsYxM81W23q3+uAjE8TrnjagGgYtNE3Zz5xp8qUBKUGr6K9ps9N8/vvO7hZouYrfWaEBlU047Ki8FQOGzoya2LJWSRDNcy8VjwYea1MVRlI7JlFQEY3A+2zK0KWyZDRENkPWTflfJ1QSZiJbL6XdEMePX0rlISoA7Zj42fgmXwxHCM6iEfw57ub6DhEk3f7FB12YY6lQtADPG74FFDPWvAhdV3km2ZMGwXkImdt/p/SyrANeq9V9Pef+NzZIvmERbg8INnBaGpSr8JN5LKLbSsshsDsJOO7sJ6jgYiREOnf199VMZEdbFDCOD6GD+r6Gi/UnbLIEp0UTnuNbeymQVHpkjqVxKGOq+bCewmPRJ33oV3k0FIZGRNNIHvBC/Wm1CDf0LhP3XBeZyEm/2v4UHohoz8qFNCpetcMy6oy9pVvCP8qwZnNMclMBsesLJnidkLTI4sBQcVIj4xyWIDriFH+ZrFuAHs47xgHqSAHxSSomPkjOULDUf8TR06qXnmrQ8p7VhnQCAh3ctZ3u704Oale0D+hQDQdzBb8nUNtYOg4e+ZEnw7MmpE6T+vBIP71c4KaSY=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then echo 'covr::coveralls(type = "all")'
  > neuroc_covr.R ; travis_wait 100 Rscript neuroc_covr.R ; rm neuroc_covr.R ; fi
