language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran --install-args=--build"
before_install:
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; fi
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
- if [[ "${PACKAGE_NAME}" == "ROpenCVLite" ]]; then shopt -s expand_aliases ; x=`Rscript
  -e "cat(Sys.which('R'))"` ; alias R="travis_wait 100 ${x}" ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: oRGpQNk2tRN4PnCa5sgO0HZeSK/+utU+ZxGT96gvHsHgHplzDzJZx0lM7+E7/i86fyJli2pwVHYCUyoSzc5llEWzV/oIPR310MXg6guYqIDnW63Td+/KbpLEBWlmppHzUgdyaRZkTKl3/N7g3dBCWSQHfumfFuTVZGAtOhPROzFrjSqVgNZJMNpHhJsNWsa3fY1Ov/S03n7xRfhYBUcHxLIC3Tahq3VVOoiz5U4kcsFZfKdJLAqqZIphaFyt9AmgQVI49DYkWeGTZcqvB40iqkYPDqtTEivsgFBiZ3W6J0hT9I9XW4c/N3OwCrzWxKwDbNkzXxSPove3qM8XfZ5B6x+CaLRlo1oaa57+mXn1fRRTNQyl9DRMPemNfMJAJQfTmyV881QNOwsx8k//ha99hHuD39Souof2KWzVzqxL2qd/TJXDZtTzv6gxlqa9mWCStGJ6k4wOxlPsB2d1JewZk63EgC4BBhPbwUrvblA43Bt2RN+TfEcwujHaQR0EFgt/WvODR2VK1c7rahH3S0MdxDkO3nE0CkUFRpUhbVGi/ZWJkED/DPAd5oKbujybPY8L5H+UbOxoWj8Z1SUQok8BM0HeFJ715GGL6OBI6K5d9Lrz3kdKwnwoJqdR//fk4/y5TAAbmk56k60TIl9atYensftmxdMaZ2j0IDGWoTr2zjo=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then echo 'covr::coveralls(type = "all")'
  > neuroc_covr.R ; travis_wait 100 Rscript neuroc_covr.R ; rm neuroc_covr.R ; fi
